#
# Copyright (c) 2015 Google, Inc
#
# SPDX-License-Identifier:      GPL-2.0+
#

ccflags-y += -DPNG_NO_LIMITS_H -DNOBYFOUR

#obj-y += compress.o deflate.o infback.o trees.o uncompr.o

obj-y += png.o pngerror.o pngget.o pngmem.o \
	 pngpread.o pngread.o pngrio.o pngrtran.o \
	 pngrutil.o pngset.o pngtrans.o

obj-y += bl2pngz.o
